### ISSUE TITLE
[Bug] Not using defValue argument in getXXXF method

### ISSUE THREAD

**Issue by jasonlaw** [AndriousSolutions/prefs#2]
Hi @Drawner ,

For all the async get methods, the default value argument is not used when calling from the instance.

Here is an example:
~~~flutter
/// Returns a Future.
  static Future<String> getStringF(String key, [String defValue]) async {
    String value;
    if (_prefsInstance == null) {
      var prefs = await _instance;
      value = prefs?.getString(key) ?? defValue ?? "";
    } else {
      value = getString(key); // [BUG] Not passing in the defValue
    }
    return value;
  }
~~~

**Comment by Andrious** [comment]
I will look into it right away...

Thanks.

**Comment by jasonlaw** [comment]
Btw, from the above code, if the _prefsInstance is null, why not call the init() method? 
From what I understand from the code, the _prefsInstance will always remain null if init() is not called at the first place.

**Comment by Andrious** [comment]
Yes, that was a consideration early on, but then I made this code to be used by the general population. Making packages for public use requires it be almost 'fool proof.' You see, it's just important to run the dispose() method as is the init() method since the _prefsInstance  is such a 'heavy resource' in memory----dispose() clears it from memory.

If I made it so a user didn't have to call the init() method, then one day someone will not call the dispose() method either. This way I am sort of 'training' the user to is it properly. You know what I mean? 

"if you us Prefs, you must call init() and dispose()"   

These are the kind of things you have to consider when making such Dart packages for public consumption.

The latest version, 3.0.1, is now available.  I couldn't believe no one saw that bug until now. Thanks very much, Jason.

Greg.
